//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seeing_I_Go_toy_project.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seeing_I_Go_toy_project.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 About Seeing-I-Go 的當地語系化字串。
        /// </summary>
        internal static string ABOUT_SEEING_I_GO_STRING {
            get {
                return ResourceManager.GetString("ABOUT_SEEING_I_GO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 agree 的當地語系化字串。
        /// </summary>
        internal static string AGREE_STRING {
            get {
                return ResourceManager.GetString("AGREE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete all maps? 的當地語系化字串。
        /// </summary>
        internal static string ASK_IF_CANCEL_ALL_MAP_STRING {
            get {
                return ResourceManager.GetString("ASK_IF_CANCEL_ALL_MAP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure you want to delete  的當地語系化字串。
        /// </summary>
        internal static string ASK_IF_CANCEL_MAP_STRING {
            get {
                return ResourceManager.GetString("ASK_IF_CANCEL_MAP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to leave app? 的當地語系化字串。
        /// </summary>
        internal static string ASK_LEAVE_APP_STRING {
            get {
                return ResourceManager.GetString("ASK_LEAVE_APP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please keep it have at least  one navigation graph. 的當地語系化字串。
        /// </summary>
        internal static string AT_LEAST_ONE_STRING {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Auto Adjust 的當地語系化字串。
        /// </summary>
        internal static string AUTO_ADJUST_STRING {
            get {
                return ResourceManager.GetString("AUTO_ADJUST_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This clinics or examination room is not available now, do you still want to go? 的當地語系化字串。
        /// </summary>
        internal static string AVAILABLE_CLINICS_NOW_STRING {
            get {
                return ResourceManager.GetString("AVAILABLE_CLINICS_NOW_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to avoid all connection types 的當地語系化字串。
        /// </summary>
        internal static string AVOID_ALL_CONNECTION_TYPE_STRING {
            get {
                return ResourceManager.GetString("AVOID_ALL_CONNECTION_TYPE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Avoid Elevator 的當地語系化字串。
        /// </summary>
        internal static string AVOID_ELEVATOR_STRING {
            get {
                return ResourceManager.GetString("AVOID_ELEVATOR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Avoid Escalator 的當地語系化字串。
        /// </summary>
        internal static string AVOID_ESCALATOR_STRING {
            get {
                return ResourceManager.GetString("AVOID_ESCALATOR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Avoid Stair 的當地語系化字串。
        /// </summary>
        internal static string AVOID_STAIR_STRING {
            get {
                return ResourceManager.GetString("AVOID_STAIR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back 的當地語系化字串。
        /// </summary>
        internal static string BACK_STRING {
            get {
                return ResourceManager.GetString("BACK_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BiDaE Tech Indoor Navigator 的當地語系化字串。
        /// </summary>
        internal static string BIDAE_NAVIGATOR_STRING {
            get {
                return ResourceManager.GetString("BIDAE_NAVIGATOR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 cancel 的當地語系化字串。
        /// </summary>
        internal static string CANCEL_STRING {
            get {
                return ResourceManager.GetString("CANCEL_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Careroom : {0} 的當地語系化字串。
        /// </summary>
        internal static string CAREROOM_STRING {
            get {
                return ResourceManager.GetString("CAREROOM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cashier and Pharmacy need to be selected at least one. 的當地語系化字串。
        /// </summary>
        internal static string CASHIER_SHOULD_SELECT_ONE_STRING {
            get {
                return ResourceManager.GetString("CASHIER_SHOULD_SELECT_ONE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bath Room 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_BATH_ROOM_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_BATH_ROOM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Blood Collection Counter 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_BLOOD_COLLECTION_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_BLOOD_COLLECTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cashier 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_CASHIER_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_CASHIER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clinics 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_CLINICS_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_CLINICS_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Conference Room 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_CONFERENCE_ROOM_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_CONFERENCE_ROOM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Convenience Store 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_CONVENIENCE_STORE_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_CONVENIENCE_STORE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Elevator 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_ELEVATOR_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_ELEVATOR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Examination Room 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_EXAMINATION_ROOM_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_EXAMINATION_ROOM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exit 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_EXIT_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_EXIT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Office 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_OFFICE_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_OFFICE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Others 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_OTHERS_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_OTHERS_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Parking 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_PARKING_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_PARKING_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pharmacy 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_PHARMACY_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_PHARMACY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stair 的當地語系化字串。
        /// </summary>
        internal static string CATEGORY_STAIR_STRING {
            get {
                return ResourceManager.GetString("CATEGORY_STAIR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Change Language 的當地語系化字串。
        /// </summary>
        internal static string CHANGE_LANGUAGE_STRING {
            get {
                return ResourceManager.GetString("CHANGE_LANGUAGE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Chinese 的當地語系化字串。
        /// </summary>
        internal static string CHINESE_STRING {
            get {
                return ResourceManager.GetString("CHINESE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Clear 的當地語系化字串。
        /// </summary>
        internal static string CLEAR_STRING {
            get {
                return ResourceManager.GetString("CLEAR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Combo Process 的當地語系化字串。
        /// </summary>
        internal static string COMBO_PROCESS_STRING {
            get {
                return ResourceManager.GetString("COMBO_PROCESS_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Command Order 的當地語系化字串。
        /// </summary>
        internal static string COMMEND_ORDER_STRING {
            get {
                return ResourceManager.GetString("COMMEND_ORDER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 en-US 的當地語系化字串。
        /// </summary>
        internal static string CULTURE_VERSION_STRING {
            get {
                return ResourceManager.GetString("CULTURE_VERSION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Current location:  的當地語系化字串。
        /// </summary>
        internal static string CURRENT_LOCATION_STRING {
            get {
                return ResourceManager.GetString("CURRENT_LOCATION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Map 的當地語系化字串。
        /// </summary>
        internal static string DELETE_MAP_STRING {
            get {
                return ResourceManager.GetString("DELETE_MAP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Goal :  的當地語系化字串。
        /// </summary>
        internal static string DESTINATION_STRING {
            get {
                return ResourceManager.GetString("DESTINATION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Destination 1 的當地語系化字串。
        /// </summary>
        internal static string DESTINATION1_STRING {
            get {
                return ResourceManager.GetString("DESTINATION1_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You are near {0}.
        ///Please go to as close to {1} as possible.
        ///Then press OK. 的當地語系化字串。
        /// </summary>
        internal static string DETECT_POSITION_CLOSE_TO_STRING {
            get {
                return ResourceManager.GetString("DETECT_POSITION_CLOSE_TO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Detecting signal... 的當地語系化字串。
        /// </summary>
        internal static string DETECT_SIGNAL_NOW_STRING {
            get {
                return ResourceManager.GetString("DETECT_SIGNAL_NOW_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have arrived the destination. 的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_ARRIVED_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_ARRIVED_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}{1}to destination 的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_ARRIVED_VIRTUAL_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_ARRIVED_VIRTUAL_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turns your back toward {0}.
        ///Then go straight for about {1}m 的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_BACK_STRAIGHT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_BACK_STRAIGHT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn your back toward {0}.
        ///Turn {1} and 
        ///then go about {2} m. 的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_BACL_TURN_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_BACL_TURN_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Take the down {0} to {1}.
        ///Upon reaching {2},
        ///{3} and then go straight about {4 }m. 的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_DOWN_COMBINE_DIRECTION_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_DOWN_COMBINE_DIRECTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Take the down {0} to{1}{2}  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_DOWN_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_DOWN_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go straight in the direction of {0}
        ///for about {1} m. 的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_FACE_STRAIGHT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_FACE_STRAIGHT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Face {0}.
        ///Turn {1} and
        ///then go about {2} m. 的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_FACE_TURN_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_FACE_TURN_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back to {0}{1}then {2}{3} And go straight about {4} m  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_INITIAIL_BACK_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_INITIAIL_BACK_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}{1}And Go Straight {2} About {3} m 的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_INITIAIL_CROSS_REGION_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_INITIAIL_CROSS_REGION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Face to {0}{1}then {2}{3} And go straight about {4} m  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_INITIAIL_FACE_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_INITIAIL_FACE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn left front{0} and go straight{1} about {2} m  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_LEFT_FRONT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_LEFT_FRONT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn left rear{0} and go straight{1} about {2} m  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_LEFT_REAR_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_LEFT_REAR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn left{0} and go straight{1} about {2} m  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_LEFT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_LEFT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn back{0} and go straight{1} about {2} m  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_REAR_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_REAR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn right front{0} and go straight{1} about {2} m  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_RIGHT_FRONT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_RIGHT_FRONT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn right rear{0} and go straight{1} about {2} m  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_RIGHT_REAR_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_RIGHT_REAR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Turn right {0} and go straight{1} about {2} m  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_RIGHT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_RIGHT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Continue to go straight  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_STRAIGHT_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_STRAIGHT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Take the up {0} to {1}.
        ///Upon reaching {2}, 
        ///{3} and then go straight about {4} m. 的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_UP_COMBINE_DIRECTION_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_UP_COMBINE_DIRECTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Take the up {0} to{1}{2}  的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_UP_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_UP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You have gone the wrong way! 的當地語系化字串。
        /// </summary>
        internal static string DIRECTION_WRONG_WAY_STRING {
            get {
                return ResourceManager.GetString("DIRECTION_WRONG_WAY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Disagree 的當地語系化字串。
        /// </summary>
        internal static string DISAGREE_STRING {
            get {
                return ResourceManager.GetString("DISAGREE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure to delete {0} ? 的當地語系化字串。
        /// </summary>
        internal static string DO_YOU_WANT_TO_DELETE_IS_STRING {
            get {
                return ResourceManager.GetString("DO_YOU_WANT_TO_DELETE_IS_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 The map that you want to download is : {0} 的當地語系化字串。
        /// </summary>
        internal static string DOWNLOAD_CHECK_STRING {
            get {
                return ResourceManager.GetString("DOWNLOAD_CHECK_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 download graph file from server 的當地語系化字串。
        /// </summary>
        internal static string DOWNLOAD_FROM_SERVER_STRING {
            get {
                return ResourceManager.GetString("DOWNLOAD_FROM_SERVER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download Map 的當地語系化字串。
        /// </summary>
        internal static string DOWNLOAD_MAP_STRING {
            get {
                return ResourceManager.GetString("DOWNLOAD_MAP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You should download navigation graph first 的當地語系化字串。
        /// </summary>
        internal static string DOWNLOAD_NAVIGATION_GRAPH_STRING {
            get {
                return ResourceManager.GetString("DOWNLOAD_NAVIGATION_GRAPH_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download QRCode Map 的當地語系化字串。
        /// </summary>
        internal static string DOWNLOAD_QRCODE_MAP_STRING {
            get {
                return ResourceManager.GetString("DOWNLOAD_QRCODE_MAP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download 的當地語系化字串。
        /// </summary>
        internal static string DOWNLOAD_STRING {
            get {
                return ResourceManager.GetString("DOWNLOAD_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Download Successfully. 的當地語系化字串。
        /// </summary>
        internal static string DOWNLOAD_SUCCESS_STRING {
            get {
                return ResourceManager.GetString("DOWNLOAD_SUCCESS_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Doctor : {0} 的當地語系化字串。
        /// </summary>
        internal static string DRNAME_STRING {
            get {
                return ResourceManager.GetString("DRNAME_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Edit 的當地語系化字串。
        /// </summary>
        internal static string EDIT_STRING {
            get {
                return ResourceManager.GetString("EDIT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Elevator 的當地語系化字串。
        /// </summary>
        internal static string ELEVATOR_STRING {
            get {
                return ResourceManager.GetString("ELEVATOR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Take Elevator to {0} floor. 的當地語系化字串。
        /// </summary>
        internal static string ELEVATOR_TO_FLOOR_STRING {
            get {
                return ResourceManager.GetString("ELEVATOR_TO_FLOOR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 English 的當地語系化字串。
        /// </summary>
        internal static string ENGLISH_STRING {
            get {
                return ResourceManager.GetString("ENGLISH_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Error 的當地語系化字串。
        /// </summary>
        internal static string ERROR_STRING {
            get {
                return ResourceManager.GetString("ERROR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Fail to delete the map 的當地語系化字串。
        /// </summary>
        internal static string ERROR_TO_DELETE_STRING {
            get {
                return ResourceManager.GetString("ERROR_TO_DELETE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Escalator 的當地語系化字串。
        /// </summary>
        internal static string ESCALATOR_STRING {
            get {
                return ResourceManager.GetString("ESCALATOR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Swap 的當地語系化字串。
        /// </summary>
        internal static string EXCHANGE_STRING {
            get {
                return ResourceManager.GetString("EXCHANGE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exit hospital 的當地語系化字串。
        /// </summary>
        internal static string EXIT_HOSPITAL_STRING {
            get {
                return ResourceManager.GetString("EXIT_HOSPITAL_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Failed to download the map 的當地語系化字串。
        /// </summary>
        internal static string FAILED_DOWNLOAD_MAP_STRING {
            get {
                return ResourceManager.GetString("FAILED_DOWNLOAD_MAP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Feedback 的當地語系化字串。
        /// </summary>
        internal static string FEEDBACK_STRING {
            get {
                return ResourceManager.GetString("FEEDBACK_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You finish today schedule. 的當地語系化字串。
        /// </summary>
        internal static string FINISH_SCHEDULE_STRING {
            get {
                return ResourceManager.GetString("FINISH_SCHEDULE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Finish 的當地語系化字串。
        /// </summary>
        internal static string FINISH_STRING {
            get {
                return ResourceManager.GetString("FINISH_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 flash 的當地語系化字串。
        /// </summary>
        internal static string FLASH_STRING {
            get {
                return ResourceManager.GetString("FLASH_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Floor  的當地語系化字串。
        /// </summary>
        internal static string FLOOR_STRING {
            get {
                return ResourceManager.GetString("FLOOR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pharmacy 的當地語系化字串。
        /// </summary>
        internal static string GET_MEDICINE_STRING {
            get {
                return ResourceManager.GetString("GET_MEDICINE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go to navigation homepage 的當地語系化字串。
        /// </summary>
        internal static string GO_NAVIGATION_HOME_PAGE_STRING {
            get {
                return ResourceManager.GetString("GO_NAVIGATION_HOME_PAGE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go to settings page 的當地語系化字串。
        /// </summary>
        internal static string GO_SETTING_PAGE_STRING {
            get {
                return ResourceManager.GetString("GO_SETTING_PAGE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go Straight 的當地語系化字串。
        /// </summary>
        internal static string GO_STRAIGHT_STRING {
            get {
                return ResourceManager.GetString("GO_STRAIGHT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Go 的當地語系化字串。
        /// </summary>
        internal static string GO_STRING {
            get {
                return ResourceManager.GetString("GO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Setting 的當地語系化字串。
        /// </summary>
        internal static string GO_TO_SETTING {
            get {
                return ResourceManager.GetString("GO_TO_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 it seems that server doesn&apos;t response, do you want to retry? 的當地語系化字串。
        /// </summary>
        internal static string HAPPEND_ERROR_STRING {
            get {
                return ResourceManager.GetString("HAPPEND_ERROR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Home 的當地語系化字串。
        /// </summary>
        internal static string HOME_STRING {
            get {
                return ResourceManager.GetString("HOME_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hope all is well with you! 的當地語系化字串。
        /// </summary>
        internal static string HOPE_STRING {
            get {
                return ResourceManager.GetString("HOPE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NTUH Yunlin Branch 的當地語系化字串。
        /// </summary>
        internal static string HOSPITAL_NAME_STRING {
            get {
                return ResourceManager.GetString("HOSPITAL_NAME_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Icons 的當地語系化字串。
        /// </summary>
        internal static string ICON_STRING {
            get {
                return ResourceManager.GetString("ICON_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IDentity Number  的當地語系化字串。
        /// </summary>
        internal static string IDNUM_STRING {
            get {
                return ResourceManager.GetString("IDNUM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This ID number is illegal, please check again. 的當地語系化字串。
        /// </summary>
        internal static string IDNUM_TYPE_WRONG_STRING {
            get {
                return ResourceManager.GetString("IDNUM_TYPE_WRONG_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reception tuning complete. Thank you. 的當地語系化字串。
        /// </summary>
        internal static string IF_NOT_STABLEGO_TO_PREFER_STRING {
            get {
                return ResourceManager.GetString("IF_NOT_STABLEGO_TO_PREFER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Info 的當地語系化字串。
        /// </summary>
        internal static string INFO_STRING {
            get {
                return ResourceManager.GetString("INFO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input your ID number 的當地語系化字串。
        /// </summary>
        internal static string INPUT_ID_NUMBER_STRING {
            get {
                return ResourceManager.GetString("INPUT_ID_NUMBER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the map name 的當地語系化字串。
        /// </summary>
        internal static string INPUT_MAP_NAME_STRING {
            get {
                return ResourceManager.GetString("INPUT_MAP_NAME_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please input your patient ID 的當地語系化字串。
        /// </summary>
        internal static string INPUT_PATIENT_ID_STRING {
            get {
                return ResourceManager.GetString("INPUT_PATIENT_ID_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (Invalid waypoint) 的當地語系化字串。
        /// </summary>
        internal static string INVALID_WAYPOINT_STRING {
            get {
                return ResourceManager.GetString("INVALID_WAYPOINT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Lab 的當地語系化字串。
        /// </summary>
        internal static string LAB_STRING {
            get {
                return ResourceManager.GetString("LAB_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you want to leave the app? 的當地語系化字串。
        /// </summary>
        internal static string LEAVE_APP_STRING {
            get {
                return ResourceManager.GetString("LEAVE_APP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LEAVE 的當地語系化字串。
        /// </summary>
        internal static string LEAVE_STRING {
            get {
                return ResourceManager.GetString("LEAVE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 License and Privacy 的當地語系化字串。
        /// </summary>
        internal static string LICENSE_AND_PRIVACY_STRING {
            get {
                return ResourceManager.GetString("LICENSE_AND_PRIVACY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 License 的當地語系化字串。
        /// </summary>
        internal static string LICENSE_STRING {
            get {
                return ResourceManager.GetString("LICENSE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Locations 的當地語系化字串。
        /// </summary>
        internal static string LOCATION_STRING {
            get {
                return ResourceManager.GetString("LOCATION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Login 的當地語系化字串。
        /// </summary>
        internal static string LOGIN_STRING {
            get {
                return ResourceManager.GetString("LOGIN_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Manual Adjust 的當地語系化字串。
        /// </summary>
        internal static string MANUAL_ADJUST_STRING {
            get {
                return ResourceManager.GetString("MANUAL_ADJUST_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Map Name 的當地語系化字串。
        /// </summary>
        internal static string MAP_NAME_STRING {
            get {
                return ResourceManager.GetString("MAP_NAME_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MAP 的當地語系化字串。
        /// </summary>
        internal static string MAP_STRING {
            get {
                return ResourceManager.GetString("MAP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Medium  的當地語系化字串。
        /// </summary>
        internal static string MEDIUM_STRING {
            get {
                return ResourceManager.GetString("MEDIUM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Message 的當地語系化字串。
        /// </summary>
        internal static string MESSAGE_STRING {
            get {
                return ResourceManager.GetString("MESSAGE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Navigate to register station 的當地語系化字串。
        /// </summary>
        internal static string NAVIGATE_TO_REGISTER_STRING {
            get {
                return ResourceManager.GetString("NAVIGATE_TO_REGISTER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Navigation List 的當地語系化字串。
        /// </summary>
        internal static string NAVIGATION_LIST_STRING {
            get {
                return ResourceManager.GetString("NAVIGATION_LIST_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WPIN 的當地語系化字串。
        /// </summary>
        internal static string NAVIGATION_STRING {
            get {
                return ResourceManager.GetString("NAVIGATION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Do you need to register? 的當地語系化字串。
        /// </summary>
        internal static string NEED_REGISTER_STRING {
            get {
                return ResourceManager.GetString("NEED_REGISTER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Never show this again 的當地語系化字串。
        /// </summary>
        internal static string NEVER_SHOW_STRING {
            get {
                return ResourceManager.GetString("NEVER_SHOW_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add 的當地語系化字串。
        /// </summary>
        internal static string NEW_STRING {
            get {
                return ResourceManager.GetString("NEW_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Bluetooth is not available, would you want to go to Setting? 的當地語系化字串。
        /// </summary>
        internal static string NO_BLUETOOTH_GO_SETTING_STRING {
            get {
                return ResourceManager.GetString("NO_BLUETOOTH_GO_SETTING_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GPS service is not available, would you want to go to Setting? 的當地語系化字串。
        /// </summary>
        internal static string NO_GPS_GO_SETTING_STRING {
            get {
                return ResourceManager.GetString("NO_GPS_GO_SETTING_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There is no network, please check it and try again 的當地語系化字串。
        /// </summary>
        internal static string NO_NETWORK_STRING {
            get {
                return ResourceManager.GetString("NO_NETWORK_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There is no clinic have been completed, so revisit couldn&apos;t be add. 的當地語系化字串。
        /// </summary>
        internal static string NO_REVISIT_RECORD_STRING {
            get {
                return ResourceManager.GetString("NO_REVISIT_RECORD_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a destination at least 的當地語系化字串。
        /// </summary>
        internal static string NO_SELECT_DESTINATION_STRING {
            get {
                return ResourceManager.GetString("NO_SELECT_DESTINATION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There is no item that could be switched. 的當地語系化字串。
        /// </summary>
        internal static string NO_SHIFT_STRING {
            get {
                return ResourceManager.GetString("NO_SHIFT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please go to any intersection 的當地語系化字串。
        /// </summary>
        internal static string NO_SIGNAL_STRING {
            get {
                return ResourceManager.GetString("NO_SIGNAL_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please go to any intersection, and tap start button to start auto adjustment. 的當地語系化字串。
        /// </summary>
        internal static string NO_SIGNAL_TAP_START_STRING {
            get {
                return ResourceManager.GetString("NO_SIGNAL_TAP_START_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pleae go to any instersection, then press button to start auto adjust 的當地語系化字串。
        /// </summary>
        internal static string NO_SINGNAL_TAP_START_STRING {
            get {
                return ResourceManager.GetString("NO_SINGNAL_TAP_START_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No 的當地語系化字串。
        /// </summary>
        internal static string NO_STRING {
            get {
                return ResourceManager.GetString("NO_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NormalHallway 的當地語系化字串。
        /// </summary>
        internal static string NORMALHALLWAY_STRING {
            get {
                return ResourceManager.GetString("NORMALHALLWAY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Notify 的當地語系化字串。
        /// </summary>
        internal static string NOTIFY_STRING {
            get {
                return ResourceManager.GetString("NOTIFY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Null  的當地語系化字串。
        /// </summary>
        internal static string NULL_STRING {
            get {
                return ResourceManager.GetString("NULL_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        internal static string OK_STRING {
            get {
                return ResourceManager.GetString("OK_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Others 的當地語系化字串。
        /// </summary>
        internal static string OTHERS_STRING {
            get {
                return ResourceManager.GetString("OTHERS_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Cashier 的當地語系化字串。
        /// </summary>
        internal static string PAYMENT_STRING {
            get {
                return ResourceManager.GetString("PAYMENT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You can go pharmacy only if you finish cashier. 的當地語系化字串。
        /// </summary>
        internal static string PHARMACY_ALERT_STRING {
            get {
                return ResourceManager.GetString("PHARMACY_ALERT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pick Destination  的當地語系化字串。
        /// </summary>
        internal static string PICK_DESTINATION_STRING {
            get {
                return ResourceManager.GetString("PICK_DESTINATION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please pick exit you want to leave. 的當地語系化字串。
        /// </summary>
        internal static string PICK_EXIT_STRING {
            get {
                return ResourceManager.GetString("PICK_EXIT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 【Click picture to select the destination】 的當地語系化字串。
        /// </summary>
        internal static string PICK_LOCATION_STRING {
            get {
                return ResourceManager.GetString("PICK_LOCATION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pick Region  的當地語系化字串。
        /// </summary>
        internal static string PICK_REGION_STRING {
            get {
                return ResourceManager.GetString("PICK_REGION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Picture&apos;s Direction 的當地語系化字串。
        /// </summary>
        internal static string PICTURE_DIRECTION_STRING {
            get {
                return ResourceManager.GetString("PICTURE_DIRECTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Play voice test 的當地語系化字串。
        /// </summary>
        internal static string PLAY_VOICE_TEST_STRING {
            get {
                return ResourceManager.GetString("PLAY_VOICE_TEST_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please add the records that you registered, thanks. 的當地語系化字串。
        /// </summary>
        internal static string PLEASE_ADD_RECORD_TO_LIST_STRING {
            get {
                return ResourceManager.GetString("PLEASE_ADD_RECORD_TO_LIST_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please adjust avoid route type  的當地語系化字串。
        /// </summary>
        internal static string PLEASE_ADJUST_AVOID_ROUTE_STRING {
            get {
                return ResourceManager.GetString("PLEASE_ADJUST_AVOID_ROUTE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please check your Internet  的當地語系化字串。
        /// </summary>
        internal static string PLEASE_CHECK_INTERNET_STRING {
            get {
                return ResourceManager.GetString("PLEASE_CHECK_INTERNET_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please just open one option 的當地語系化字串。
        /// </summary>
        internal static string PLEASE_CONTROL_RSSI_OPTION_STRING {
            get {
                return ResourceManager.GetString("PLEASE_CONTROL_RSSI_OPTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please finsih {0} first, thank you. 的當地語系化字串。
        /// </summary>
        internal static string PLEASE_DO_SOMETHING_FIRST_STRING {
            get {
                return ResourceManager.GetString("PLEASE_DO_SOMETHING_FIRST_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please go in the direction of the arrow. 的當地語系化字串。
        /// </summary>
        internal static string PLEASE_FOLLOW_PICTURE_STRING {
            get {
                return ResourceManager.GetString("PLEASE_FOLLOW_PICTURE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select your purpose. 的當地語系化字串。
        /// </summary>
        internal static string PLEASE_SELECT_OPTION_STRING {
            get {
                return ResourceManager.GetString("PLEASE_SELECT_OPTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select why you come to the hospital. 的當地語系化字串。
        /// </summary>
        internal static string PLEASE_SELECT_YOUR_PURPOSE_STRING {
            get {
                return ResourceManager.GetString("PLEASE_SELECT_YOUR_PURPOSE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preferences 的當地語系化字串。
        /// </summary>
        internal static string PREFERENCES_STRING {
            get {
                return ResourceManager.GetString("PREFERENCES_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Privacy 的當地語系化字串。
        /// </summary>
        internal static string PRIVACY_STRING {
            get {
                return ResourceManager.GetString("PRIVACY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Qrcode Content 的當地語系化字串。
        /// </summary>
        internal static string QRCODE_CONTENT_STRING {
            get {
                return ResourceManager.GetString("QRCODE_CONTENT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Register 的當地語系化字串。
        /// </summary>
        internal static string REGISTER_STRING {
            get {
                return ResourceManager.GetString("REGISTER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Register Day 的當地語系化字串。
        /// </summary>
        internal static string REGISTERDAY_STRING {
            get {
                return ResourceManager.GetString("REGISTERDAY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Registered counter 的當地語系化字串。
        /// </summary>
        internal static string REGISTERED_COUNTER_STRING {
            get {
                return ResourceManager.GetString("REGISTERED_COUNTER_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RETRY 的當地語系化字串。
        /// </summary>
        internal static string RETRY_STRING {
            get {
                return ResourceManager.GetString("RETRY_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return 的當地語系化字串。
        /// </summary>
        internal static string RETURN_STRING {
            get {
                return ResourceManager.GetString("RETURN_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Revisit 的當地語系化字串。
        /// </summary>
        internal static string REVISIT_STRING {
            get {
                return ResourceManager.GetString("REVISIT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Route Option 的當地語系化字串。
        /// </summary>
        internal static string ROUTE_OPTION_STRING {
            get {
                return ResourceManager.GetString("ROUTE_OPTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Signal Strength Option  的當地語系化字串。
        /// </summary>
        internal static string RSSI_OPTION_STRING {
            get {
                return ResourceManager.GetString("RSSI_OPTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Scaning signal... 的當地語系化字串。
        /// </summary>
        internal static string SCAN_RSSI_NOW_STRING {
            get {
                return ResourceManager.GetString("SCAN_RSSI_NOW_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sorry! You select some duplicate process : {0} 的當地語系化字串。
        /// </summary>
        internal static string SELECT_DUMPLICATE_CONTENT_STRING {
            get {
                return ResourceManager.GetString("SELECT_DUMPLICATE_CONTENT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 You select some duplicate examination room. 的當地語系化字串。
        /// </summary>
        internal static string SELECT_DUPLICATE_EXAM_STRING {
            get {
                return ResourceManager.GetString("SELECT_DUPLICATE_EXAM_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a exit. 的當地語系化字串。
        /// </summary>
        internal static string SELECT_EXIT_STRING {
            get {
                return ResourceManager.GetString("SELECT_EXIT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Select Language 的當地語系化字串。
        /// </summary>
        internal static string SELECT_LANGUAGE_STRING {
            get {
                return ResourceManager.GetString("SELECT_LANGUAGE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Pick your goal within locations 的當地語系化字串。
        /// </summary>
        internal static string SELECT_LOCATION_STRING {
            get {
                return ResourceManager.GetString("SELECT_LOCATION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sequence : {0} 的當地語系化字串。
        /// </summary>
        internal static string SEQUENCE_STRING {
            get {
                return ResourceManager.GetString("SEQUENCE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Settings 的當地語系化字串。
        /// </summary>
        internal static string SETTING_STRING {
            get {
                return ResourceManager.GetString("SETTING_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please pick two items that you want to change position, these two will exchange their position. 的當地語系化字串。
        /// </summary>
        internal static string SHIFT_DESCRIPTION_STRING {
            get {
                return ResourceManager.GetString("SHIFT_DESCRIPTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0}Then {1},for about {2} m 的當地語系化字串。
        /// </summary>
        internal static string SPECIAL_INSTRUCTION_STRING {
            get {
                return ResourceManager.GetString("SPECIAL_INSTRUCTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stair 的當地語系化字串。
        /// </summary>
        internal static string STAIR_STRING {
            get {
                return ResourceManager.GetString("STAIR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Start 的當地語系化字串。
        /// </summary>
        internal static string START_STRING {
            get {
                return ResourceManager.GetString("START_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Strong  的當地語系化字串。
        /// </summary>
        internal static string STRONG_STRING {
            get {
                return ResourceManager.GetString("STRONG_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully Delete 的當地語系化字串。
        /// </summary>
        internal static string SUCCESSFULLY_DELETE_STRING {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_DELETE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Successfully download the map 的當地語系化字串。
        /// </summary>
        internal static string SUCCESSFULLY_DOWNLOAD_MAP_STRING {
            get {
                return ResourceManager.GetString("SUCCESSFULLY_DOWNLOAD_MAP_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Are you sure to open the website? 的當地語系化字串。
        /// </summary>
        internal static string SURE_TO_OPEN_WEBSITE_STRING {
            get {
                return ResourceManager.GetString("SURE_TO_OPEN_WEBSITE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Taipei City Hall 的當地語系化字串。
        /// </summary>
        internal static string TAIPEI_CITY_HALL_STRING {
            get {
                return ResourceManager.GetString("TAIPEI_CITY_HALL_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Thank you for coming 的當地語系化字串。
        /// </summary>
        internal static string THANK_COMING_STRING {
            get {
                return ResourceManager.GetString("THANK_COMING_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Third party license 的當地語系化字串。
        /// </summary>
        internal static string THIRDPARTY_LICENSE_STRING {
            get {
                return ResourceManager.GetString("THIRDPARTY_LICENSE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 This item can&apos;t be removed 的當地語系化字串。
        /// </summary>
        internal static string THIS_ITEM_CANT_BE_REMOVE_STRING {
            get {
                return ResourceManager.GetString("THIS_ITEM_CANT_BE_REMOVE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 turn back 的當地語系化字串。
        /// </summary>
        internal static string TURN_BACK_STRING {
            get {
                return ResourceManager.GetString("TURN_BACK_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 turn forward left  的當地語系化字串。
        /// </summary>
        internal static string TURN_LEFT_FRONT_STRING {
            get {
                return ResourceManager.GetString("TURN_LEFT_FRONT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 turn backward left 的當地語系化字串。
        /// </summary>
        internal static string TURN_LEFT_REAR_STRING {
            get {
                return ResourceManager.GetString("TURN_LEFT_REAR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 turn left 的當地語系化字串。
        /// </summary>
        internal static string TURN_LEFT_STRING {
            get {
                return ResourceManager.GetString("TURN_LEFT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 turn forward right 的當地語系化字串。
        /// </summary>
        internal static string TURN_RIGHT_FRONT_STRING {
            get {
                return ResourceManager.GetString("TURN_RIGHT_FRONT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 turn backward right 的當地語系化字串。
        /// </summary>
        internal static string TURN_RIGHT_REAR_STRING {
            get {
                return ResourceManager.GetString("TURN_RIGHT_REAR_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 turn right 的當地語系化字串。
        /// </summary>
        internal static string TURN_RIGHT_STRING {
            get {
                return ResourceManager.GetString("TURN_RIGHT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unkwown 的當地語系化字串。
        /// </summary>
        internal static string UNKNOWN_STRING {
            get {
                return ResourceManager.GetString("UNKNOWN_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 update 的當地語系化字串。
        /// </summary>
        internal static string UPDATE_STRING {
            get {
                return ResourceManager.GetString("UPDATE_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Version 的當地語系化字串。
        /// </summary>
        internal static string VERSION_STRING {
            get {
                return ResourceManager.GetString("VERSION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voice Select 的當地語系化字串。
        /// </summary>
        internal static string VOICE_SELECT_STRING {
            get {
                return ResourceManager.GetString("VOICE_SELECT_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Voice Setting 的當地語系化字串。
        /// </summary>
        internal static string VOICE_SETTING_STRING {
            get {
                return ResourceManager.GetString("VOICE_SETTING_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Welcome to use the Indoor Navigation of BiDaETech 的當地語系化字串。
        /// </summary>
        internal static string VOICE_SPEAK_STRING {
            get {
                return ResourceManager.GetString("VOICE_SPEAK_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Warning 的當地語系化字串。
        /// </summary>
        internal static string WARN_STRING {
            get {
                return ResourceManager.GetString("WARN_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yes 的當地語系化字串。
        /// </summary>
        internal static string YES_STRING {
            get {
                return ResourceManager.GetString("YES_STRING", resourceCulture);
            }
        }
    }
}
